### ISSUE TITLE
Trouble with Japanese input

### ISSUE THREAD

**Issue by plane** [racket/expeditor#11]
If I type Japanese into the new repl, it seems to have problems with column positions.  Text starts to appear in the wrong positions on the screen, and if I try to move my cursor to the left of it, I can't reach the left side of the screen.

It's a little difficult to describe, so I recorded a video of myself struggling with it:

https://www.quarplet.com/expeditor.mkv

The old repl, without the fancy syntax highlighting and such, seems to work fine with Japanese text.

**Comment by sorawee** [comment]
Similar problem for Thai. When I type `ดี` (note that `ด` and `ี` are different characters, but when they are adjacent, they stack and take only one column), I can delete twice. The first deletion appears to delete the whole `ดี` though in fact it only deletes `ี` . The second deletion eats up the prompt.

**Comment by mflatt** [comment]
Commit f6d7f431e72a248dfaa1e4728479998efa4794eb is intended to fix the problem with wide characters. It needs a development/snapshot Racket.

With 6b077d883e95ffed33d40efe8e62c9883c816e0d, then combining characters like in `ดี` are somewhat supported, but more would be needed to make them work right.

**Comment by plane** [comment]
Thank you!  Japanese text seems to be working fine again.
