### ISSUE TITLE
Weird behavior with `]` in multi-line input

### ISSUE THREAD

**Issue by plane** [racket/expeditor#14]
Type a single paren, and hit enter:

```
Welcome to Racket v8.3.0.11 [cs].
> (

```

Now press `]`, and (without pressing enter) you will see:

```
crystal@wings:~$ racket
Welcome to Racket v8.3.0.11 [cs].
> (
   ]
vector-ref: index is out of range
  index: 1
  valid range: [0, 0]
  vector: '#(1)
append: contract violation
  expected: list?
  given: #<void>
 [,bt for context]

```

Pressing `)` doesn't trigger the bug.  Typing `]` on the same line as the opening paren doesn't trigger the bug; it has to be on a separate line like this.

**Comment by mflatt** [comment]
Thanks for the report!
