### ISSUE TITLE
Multi-character parenthesis tokens

### ISSUE THREAD

**Issue by greghendershott** [racket/expeditor#6]
In these two locations:

https://github.com/racket/expeditor/blob/ebbdc126217ddc97b266763b3a5c5e9cd90fdbc2/expeditor-lib/private/object.rkt#L108
https://github.com/racket/expeditor/blob/ebbdc126217ddc97b266763b3a5c5e9cd90fdbc2/expeditor-lib/private/object.rkt#L136

I think there's a problem using `get-text` because e.g. the Racket lexer can return a `parenthesis` token whose lexeme consists of multiple characters. For example the `#(` in `#(1)`. Fortunately it also returns a `paren` value that [you put in the `paren` field of the `token` struct](https://github.com/racket/expeditor/blob/ebbdc126217ddc97b266763b3a5c5e9cd90fdbc2/expeditor-lib/private/object.rkt#L22). I think you want to use that `token-paren` value instead?

**Comment by mflatt** [comment]
Thanks!
