### ISSUE TITLE
history navigation errors

### ISSUE THREAD

**Issue by Bogdanp** [racket/expeditor#8]
I don't know if this is a general issue or something specific to my install (corrupted history maybe?), but the following series of steps breaks history navigation.

1. run `racket`
2. eval `1`
3. hit the up arrow key or `C-p`

After the third step, every command I try to issue yields an error.

```
Welcome to Racket v8.3.0.7 [cs].
> 1
1
>
car: contract violation
  expected: pair?
  given: "(thread (lambda () (fib 30)))"
append: contract violation
  expected: list?
  given: #<void>
 [,bt for context]
> a

car: contract violation
  expected: pair?
  given: "(thread (lambda () (fib 30)))"
car: contract violation
  expected: pair?
  given: "(thread (lambda () (fib 30)))"
 [,bt for context]
>
```

The line it's complaining about was indeed the last line in my history:

```
> (last (get-preference 'readline-input-history))
#"(thread (lambda () (fib 30)))"
```

After clearing out my history, everything works fine.

**Comment by mflatt** [comment]
This started happening to me, too. I guess we both hit the history limit at about the same time, because it was a problem with pruning the history when it gets beyond the limit.
